name: Build and Release Apps via FTP

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "minimal | standard | verbose"
        required: true
        default: "verbose"

  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and release app

    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install
        working-directory: .

      - name: Create locale files
        run: node ./lib/parseLocalizations.mjs
        working-directory: .

      - name: Create artwork files
        run: node ./lib/parseTopLevelContent.mjs
        working-directory: .

      - name: Create about files
        run: node ./lib/parseAboutContent.mjs
        working-directory: .

      - name: Create press files
        run: node ./lib/parsePressContent.mjs
        working-directory: .

      - name: Create artwork files
        run: node ./lib/parseArtworkContent.mjs
        working-directory: .

      - name: Compile source
        run: npm run build
        working-directory: .

      - name: Upload to host via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftp
          local-dir: /out/
          server-dir: /home/www/de.stephenwood.brigitte-smith
          log-level: ${{ github.event.inputs.logLevel }}
